services:
  RepIntel_AI:
    pull_policy: build
    image: repintelai/RepIntel_AI
    build: ./
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    restart: always
    ports:
      - 8000:8000
  repintelai-nextjs:
    pull_policy: build
    image: repintelai/repintelai-nextjs
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: frontend/nextjs
    volumes:
      - /app/node_modules
      - ./frontend/nextjs:/app
    restart: always
    ports:
      - 3000:3000

  RepIntel_AI-tests:
    image: repintelai/RepIntel_AI-tests
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
    profiles: ["test"]
    command: >
      /bin/sh -c "
      pip install pytest pytest-asyncio faiss-cpu &&
      python -m pytest tests/report-types.py &&
      python -m pytest tests/vector-store.py
      "
